spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:scarcitydata}?useSSL=false&createDatabaseIfNotExist=true&useUnicode=yes&characterSetServer=character_set_server=utf8mb4&collationServer=utf8mb4_unicode_ci
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver


    #  flyway:
    #    baseline-on-migrate: true

    jackson:
    serialization:
      fail-on-empty-beans: false
#  messages:
#    encoding: ISO-8859-1
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
    #      ddl-auto: validate
    properties:
      hibernate:
        naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

