#spring:
#  datasource:
#    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:scarcitydata}?useSSL=false&createDatabaseIfNotExist=true&useUnicode=yes&characterSetServer=character_set_server=utf8mb4&collationServer=utf8mb4_unicode_ci
#    username: root
#    password: root
#    driver-class-name: com.mysql.jdbc.Driver

spring:
  datasource:
    url: jdbc:h2:mem:AZ;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;INIT=CREATE SCHEMA IF NOT EXISTS SCARCITYDATA
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jackson:
    serialization:
      fail-on-empty-beans: false
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
        default_schema: SCARCITYDATA
        dialect: org.hibernate.dialect.H2Dialect

